// Code generated by gen/main.go; DO NOT EDIT.

package vm

import (
	"github.com/Giulio2002/gevm/opcode"
	"github.com/Giulio2002/gevm/spec"
	"github.com/Giulio2002/gevm/types"
	"github.com/holiman/uint256"
)

// Ensure imports are used.
var (
	_ = types.U256Zero
	_ = spec.GasVerylow
	_ = opcode.STOP
)

// Run executes bytecode until halted using direct switch dispatch.
// Static gas is accumulated in a local gasCounter variable. Instead of
// checking and deducting gas per-instruction, static gas costs are summed
// across a basic block and flushed (checked + deducted) at block boundaries
// (jumps, dynamic-gas opcodes, halting opcodes). This eliminates one branch
// + one memory write per static-gas instruction in the hot loop.
func (DefaultRunner) Run(interp *Interpreter, host Host) {
	bc := interp.Bytecode
	gas := &interp.Gas
	var gasCounter uint64
	for bc.running {
		op := bc.code[bc.pc]
		bc.pc++

		switch op {
		case opcode.STOP:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0

			interp.Halt(InstructionResultStop)

		case opcode.ADD:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				types.AddTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.MUL:
			gasCounter += spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				top.Mul(&a, top)

			}
		case opcode.SUB:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				types.SubTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.DIV:
			gasCounter += spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				if !types.IsZeroPtr(top) {
					top.Div(&a, top)
				}

			}
		case opcode.SDIV:
			gasCounter += spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				*top = types.SDiv(a, *top)

			}
		case opcode.MOD:
			gasCounter += spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				if !types.IsZeroPtr(top) {
					top.Mod(&a, top)
				}

			}
		case opcode.SMOD:
			gasCounter += spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				*top = types.SMod(a, *top)

			}
		case opcode.ADDMOD:
			gasCounter += spec.GasMid
			s := interp.Stack
			if s.top < 3 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top -= 2

				a := s.data[s.top+1]
				b := s.data[s.top]
				top := &s.data[s.top-1]
				top.AddMod(&a, &b, top)

			}
		case opcode.MULMOD:
			gasCounter += spec.GasMid
			s := interp.Stack
			if s.top < 3 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top -= 2

				a := s.data[s.top+1]
				b := s.data[s.top]
				top := &s.data[s.top-1]
				top.MulMod(&a, &b, top)

			}
		case opcode.EXP:
			gasCounter += spec.GasHigh
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opExp(interp)
		case opcode.SIGNEXTEND:
			gasCounter += spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				ext := s.data[s.top]
				top := &s.data[s.top-1]
				*top = types.SignExtend(ext, *top)

			}
		case opcode.LT:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				if types.LtPtr(&s.data[s.top], &s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.GT:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				if types.GtPtr(&s.data[s.top], &s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.SLT:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := &s.data[s.top]
				b := &s.data[s.top-1]
				aNeg := a[3] >> 63
				bNeg := b[3] >> 63
				var lt bool
				if aNeg != bNeg {
					lt = aNeg > bNeg
				} else {
					lt = types.LtPtr(a, b)
				}
				if lt {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.SGT:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := &s.data[s.top]
				b := &s.data[s.top-1]
				aNeg := a[3] >> 63
				bNeg := b[3] >> 63
				var gt bool
				if aNeg != bNeg {
					gt = bNeg > aNeg
				} else {
					gt = types.GtPtr(a, b)
				}
				if gt {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.EQ:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				if types.EqPtr(&s.data[s.top], &s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.ISZERO:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top == 0 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {

				if types.IsZeroPtr(&s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.AND:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				types.AndTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.OR:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				types.OrTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.XOR:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				types.XorTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.NOT:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top == 0 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {

				types.NotTo(&s.data[s.top-1], &s.data[s.top-1])

			}
		case opcode.BYTE:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				idx := types.U256AsUsizeSaturated(&a)
				if idx < 32 {
					*top = types.U256From(uint64(types.U256ByteBE(top, uint(idx))))
				} else {
					*top = types.U256Zero
				}

			}
		case opcode.SHL:
			gasCounter += spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top < 2 {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltUnderflow()
				} else {
					s.top--

					shift := s.data[s.top]
					top := &s.data[s.top-1]
					sa := types.U256AsUsizeSaturated(&shift)
					if sa < 256 {
						top.Lsh(top, uint(sa))
					} else {
						*top = types.U256Zero
					}

				}
			}
		case opcode.SHR:
			gasCounter += spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top < 2 {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltUnderflow()
				} else {
					s.top--

					shift := s.data[s.top]
					top := &s.data[s.top-1]
					sa := types.U256AsUsizeSaturated(&shift)
					if sa < 256 {
						top.Rsh(top, uint(sa))
					} else {
						*top = types.U256Zero
					}

				}
			}
		case opcode.SAR:
			gasCounter += spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top < 2 {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltUnderflow()
				} else {
					s.top--

					shift := s.data[s.top]
					top := &s.data[s.top-1]
					sa := types.U256AsUsizeSaturated(&shift)
					if sa < 256 {
						top.SRsh(top, uint(sa))
					} else if types.U256Bit(top, 255) {
						*top = types.U256Max
					} else {
						*top = types.U256Zero
					}

				}
			}
		case opcode.CLZ:
			gasCounter += spec.GasLow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Osaka) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top == 0 {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltUnderflow()
				} else {

					top := &s.data[s.top-1]
					*top = types.U256From(uint64(types.U256LeadingZeros(top)))

				}
			}
		case opcode.KECCAK256:
			gasCounter += spec.GasKeccak256
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opKeccak256(interp)
		case opcode.ADDRESS:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = interp.Input.TargetAddress.ToU256()
				s.top++

			}
		case opcode.BALANCE:
			gasCounter += interp.ForkGas.Balance
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opBalance(interp, host)
		case opcode.ORIGIN:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				addr := host.Caller()
				s.data[s.top] = addr.ToU256()
				s.top++

			}
		case opcode.CALLER:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = interp.Input.CallerAddress.ToU256()
				s.top++

			}
		case opcode.CALLVALUE:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = interp.Input.CallValue
				s.top++

			}
		case opcode.CALLDATALOAD:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top == 0 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {

				top := &s.data[s.top-1]
				offset := types.U256AsUsizeSaturated(top)
				input := interp.Input.Input
				var word [32]byte
				if offset < uint64(len(input)) {
					src := input[offset:]
					if len(src) >= 32 {
						copy(word[:], src[:32])
					} else {
						copy(word[:], src)
					}
				}
				*top = types.U256FromBytes32(word)

			}
		case opcode.CALLDATASIZE:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(len(interp.Input.Input)))
				s.top++

			}
		case opcode.CALLDATACOPY:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opCalldatacopy(interp)
		case opcode.CODESIZE:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(bc.originalLen))
				s.top++

			}
		case opcode.CODECOPY:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opCodecopy(interp)
		case opcode.GASPRICE:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.EffectiveGasPrice()
				s.top++

			}
		case opcode.EXTCODESIZE:
			gasCounter += interp.ForkGas.ExtCodeSize
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opExtcodesize(interp, host)
		case opcode.EXTCODECOPY:
			gasCounter += interp.ForkGas.ExtCodeSize
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opExtcodecopy(interp, host)
		case opcode.RETURNDATASIZE:
			gasCounter += spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {

					s.data[s.top] = types.U256From(uint64(len(interp.ReturnData)))
					s.top++

				}
			}
		case opcode.RETURNDATACOPY:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				opReturndatacopy(interp)
			}
		case opcode.EXTCODEHASH:
			gasCounter += interp.ForkGas.ExtCodeHash
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				interp.HaltNotActivated()
			} else {
				opExtcodehash(interp, host)
			}
		case opcode.BLOCKHASH:
			gasCounter += spec.GasBlockhash
			s := interp.Stack
			if s.top == 0 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {

				top := &s.data[s.top-1]
				hash := host.BlockHash(*top)
				*top = hash.ToU256()

			}
		case opcode.COINBASE:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				addr := host.Beneficiary()
				s.data[s.top] = addr.ToU256()
				s.top++

			}
		case opcode.TIMESTAMP:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.Timestamp()
				s.top++

			}
		case opcode.NUMBER:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.BlockNumber()
				s.top++

			}
		case opcode.DIFFICULTY:
			gasCounter += spec.GasBase
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opDifficulty(interp, host)
		case opcode.GASLIMIT:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.GasLimit()
				s.top++

			}
		case opcode.CHAINID:
			gasCounter += spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Istanbul) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {
					opChainid(interp, host)
				}
			}
		case opcode.SELFBALANCE:
			gasCounter += spec.GasLow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Istanbul) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {
					opSelfbalance(interp, host)
				}
			}
		case opcode.BASEFEE:
			gasCounter += spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.London) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {
					opBasefee(interp, host)
				}
			}
		case opcode.BLOBHASH:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opBlobhash(interp, host)
			}
		case opcode.BLOBBASEFEE:
			gasCounter += spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {
					opBlobbasefee(interp, host)
				}
			}
		case opcode.SLOTNUM:
			gasCounter += spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {
					opSlotnum(interp, host)
				}
			}
		case opcode.POP:
			gasCounter += spec.GasBase
			if interp.Stack.top == 0 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltUnderflow()
			} else {

				interp.Stack.top--

			}
		case opcode.MLOAD:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0

			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
				return
			}
			top := &s.data[s.top-1]
			if top[1]|top[2]|top[3] == 0 {
				offset := int(top[0])
				if offset >= 0 && offset+32 <= interp.Memory.Len() {
					*top = interp.Memory.GetU256(offset)
				} else {
					if interp.ResizeMemory(offset, 32) {
						*top = interp.Memory.GetU256(offset)
					}
				}
			} else {
				interp.Halt(InstructionResultInvalidOperandOOG)
			}

		case opcode.MSTORE:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0

			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
				return
			}
			s.top -= 2
			offsetVal := s.data[s.top+1]
			value := s.data[s.top]
			if offsetVal[1]|offsetVal[2]|offsetVal[3] == 0 {
				offset := int(offsetVal[0])
				if offset >= 0 && offset+32 <= interp.Memory.Len() {
					interp.Memory.SetU256(offset, value)
				} else {
					if interp.ResizeMemory(offset, 32) {
						interp.Memory.SetU256(offset, value)
					}
				}
			} else {
				interp.Halt(InstructionResultInvalidOperandOOG)
			}

		case opcode.MSTORE8:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opMstore8(interp)
		case opcode.SLOAD:
			gasCounter += interp.ForkGas.Sload
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opSload(interp, host)
		case opcode.SSTORE:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opSstore(interp, host)
		case opcode.JUMP:
			gasCounter += spec.GasMid
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0

			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
				return
			}
			s.top--
			target := s.data[s.top]
			if target[1]|target[2]|target[3] != 0 {
				interp.Halt(InstructionResultInvalidJump)
				return
			}
			dest := int(target[0])
			bc := bc
			if dest >= bc.originalLen || bc.code[dest] != opcode.JUMPDEST {
				interp.Halt(InstructionResultInvalidJump)
				return
			}
			bc.ensureJumpTable()
			if bc.jumpTable[dest/8]&(1<<(uint(dest)%8)) == 0 {
				interp.Halt(InstructionResultInvalidJump)
				return
			}
			bc.pc = dest

		case opcode.JUMPI:
			gasCounter += spec.GasHigh
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0

			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
				return
			}
			s.top -= 2
			cond := s.data[s.top]
			target := s.data[s.top+1]
			if !cond.IsZero() {
				if target[1]|target[2]|target[3] != 0 {
					interp.Halt(InstructionResultInvalidJump)
					return
				}
				dest := int(target[0])
				bc := bc
				if dest >= bc.originalLen || bc.code[dest] != opcode.JUMPDEST {
					interp.Halt(InstructionResultInvalidJump)
					return
				}
				bc.ensureJumpTable()
				if bc.jumpTable[dest/8]&(1<<(uint(dest)%8)) == 0 {
					interp.Halt(InstructionResultInvalidJump)
					return
				}
				bc.pc = dest
			}

		case opcode.PC:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(bc.pc - 1))
				s.top++

			}
		case opcode.MSIZE:
			gasCounter += spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(interp.Memory.Len()))
				s.top++

			}
		case opcode.GAS:
			gasCounter += spec.GasBase
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opGas(interp)
		case opcode.JUMPDEST:
			gasCounter += spec.GasJumpdest
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
		case opcode.TLOAD:
			gasCounter += spec.GasWarmStorageReadCost
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opTload(interp, host)
			}
		case opcode.TSTORE:
			gasCounter += spec.GasWarmStorageReadCost
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opTstore(interp, host)
			}
		case opcode.MCOPY:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opMcopy(interp)
			}
		case opcode.DUPN:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				opDupN(interp)
			}
		case opcode.SWAPN:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				opSwapN(interp)
			}
		case opcode.EXCHANGE:
			gasCounter += spec.GasVerylow
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				opExchange(interp)
			}
		case opcode.CREATE:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opCreate(interp, host)
		case opcode.CALL:
			gasCounter += interp.ForkGas.Call
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opCall(interp, host)
		case opcode.CALLCODE:
			gasCounter += interp.ForkGas.Call
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opCallcode(interp, host)
		case opcode.RETURN:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opReturn(interp)
		case opcode.DELEGATECALL:
			gasCounter += interp.ForkGas.Call
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Homestead) {
				interp.HaltNotActivated()
			} else {
				opDelegatecall(interp, host)
			}
		case opcode.CREATE2:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Petersburg) {
				interp.HaltNotActivated()
			} else {
				opCreate2(interp, host)
			}
		case opcode.STATICCALL:
			gasCounter += interp.ForkGas.Call
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				opStaticcall(interp, host)
			}
		case opcode.REVERT:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				opRevert(interp)
			}
		case opcode.INVALID:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0

			interp.Halt(InstructionResultInvalidFEOpcode)

		case opcode.SELFDESTRUCT:
			gasCounter += interp.ForkGas.Selfdestruct
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			opSelfdestruct(interp, host)
		case opcode.PUSH0:
			gasCounter += spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Shanghai) {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					if gas.remaining < gasCounter {
						interp.HaltOOG()
						return
					}
					gas.remaining -= gasCounter
					gasCounter = 0
					interp.HaltOverflow()
				} else {

					s.data[s.top] = types.U256Zero
					s.top++

				}
			}
		case opcode.PUSH1:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				s.data[s.top] = uint256.Int{uint64(bc.code[bc.pc]), 0, 0, 0}
				bc.pc++
				s.top++

			}
		case opcode.PUSH2:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				v := uint64(bc.code[bc.pc])<<8 | uint64(bc.code[bc.pc+1])
				bc.pc += 2
				s.data[s.top] = uint256.Int{v, 0, 0, 0}
				s.top++

			}
		case opcode.PUSH3:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				v := uint64(c[p])<<16 | uint64(c[p+1])<<8 | uint64(c[p+2])
				bc.pc = p + 3
				s.data[s.top] = uint256.Int{v, 0, 0, 0}
				s.top++

			}
		case opcode.PUSH4:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				v := uint64(c[p])<<24 | uint64(c[p+1])<<16 | uint64(c[p+2])<<8 | uint64(c[p+3])
				bc.pc = p + 4
				s.data[s.top] = uint256.Int{v, 0, 0, 0}
				s.top++

			}
		case opcode.PUSH20:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				// 20 bytes = limb2 (4 bytes) + limb1 (8 bytes) + limb0 (8 bytes)
				l2 := uint64(c[p])<<24 | uint64(c[p+1])<<16 | uint64(c[p+2])<<8 | uint64(c[p+3])
				l1 := uint64(c[p+4])<<56 | uint64(c[p+5])<<48 | uint64(c[p+6])<<40 | uint64(c[p+7])<<32 |
					uint64(c[p+8])<<24 | uint64(c[p+9])<<16 | uint64(c[p+10])<<8 | uint64(c[p+11])
				l0 := uint64(c[p+12])<<56 | uint64(c[p+13])<<48 | uint64(c[p+14])<<40 | uint64(c[p+15])<<32 |
					uint64(c[p+16])<<24 | uint64(c[p+17])<<16 | uint64(c[p+18])<<8 | uint64(c[p+19])
				bc.pc = p + 20
				s.data[s.top] = uint256.Int{l0, l1, l2, 0}
				s.top++

			}
		case opcode.PUSH32:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				l3 := uint64(c[p])<<56 | uint64(c[p+1])<<48 | uint64(c[p+2])<<40 | uint64(c[p+3])<<32 |
					uint64(c[p+4])<<24 | uint64(c[p+5])<<16 | uint64(c[p+6])<<8 | uint64(c[p+7])
				l2 := uint64(c[p+8])<<56 | uint64(c[p+9])<<48 | uint64(c[p+10])<<40 | uint64(c[p+11])<<32 |
					uint64(c[p+12])<<24 | uint64(c[p+13])<<16 | uint64(c[p+14])<<8 | uint64(c[p+15])
				l1 := uint64(c[p+16])<<56 | uint64(c[p+17])<<48 | uint64(c[p+18])<<40 | uint64(c[p+19])<<32 |
					uint64(c[p+20])<<24 | uint64(c[p+21])<<16 | uint64(c[p+22])<<8 | uint64(c[p+23])
				l0 := uint64(c[p+24])<<56 | uint64(c[p+25])<<48 | uint64(c[p+26])<<40 | uint64(c[p+27])<<32 |
					uint64(c[p+28])<<24 | uint64(c[p+29])<<16 | uint64(c[p+30])<<8 | uint64(c[p+31])
				bc.pc = p + 32
				s.data[s.top] = uint256.Int{l0, l1, l2, l3}
				s.top++

			}
		case opcode.PUSH5, opcode.PUSH6, opcode.PUSH7, opcode.PUSH8, opcode.PUSH9, opcode.PUSH10, opcode.PUSH11, opcode.PUSH12, opcode.PUSH13, opcode.PUSH14, opcode.PUSH15, opcode.PUSH16, opcode.PUSH17, opcode.PUSH18, opcode.PUSH19, opcode.PUSH21, opcode.PUSH22, opcode.PUSH23, opcode.PUSH24, opcode.PUSH25, opcode.PUSH26, opcode.PUSH27, opcode.PUSH28, opcode.PUSH29, opcode.PUSH30, opcode.PUSH31:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				n := int(op - opcode.PUSH0)
				s.data[s.top] = types.U256FromBytes(bc.code[bc.pc : bc.pc+n])
				bc.pc += n
				s.top++
			}
		case opcode.DUP1:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 1 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-1]
				s.top++
			}
		case opcode.DUP2:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 2 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-2]
				s.top++
			}
		case opcode.DUP3:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 3 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-3]
				s.top++
			}
		case opcode.DUP4:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 4 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-4]
				s.top++
			}
		case opcode.DUP5:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 5 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-5]
				s.top++
			}
		case opcode.DUP6:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 6 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-6]
				s.top++
			}
		case opcode.DUP7:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 7 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-7]
				s.top++
			}
		case opcode.DUP8:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 8 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-8]
				s.top++
			}
		case opcode.DUP9:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 9 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-9]
				s.top++
			}
		case opcode.DUP10:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 10 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-10]
				s.top++
			}
		case opcode.DUP11:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 11 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-11]
				s.top++
			}
		case opcode.DUP12:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 12 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-12]
				s.top++
			}
		case opcode.DUP13:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 13 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-13]
				s.top++
			}
		case opcode.DUP14:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 14 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-14]
				s.top++
			}
		case opcode.DUP15:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 15 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-15]
				s.top++
			}
		case opcode.DUP16:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			if s.top < 16 || s.top >= StackLimit {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-16]
				s.top++
			}
		case opcode.SWAP1:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 1 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-1] = s.data[t-1], s.data[t]
			}
		case opcode.SWAP2:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 2 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-2] = s.data[t-2], s.data[t]
			}
		case opcode.SWAP3:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 3 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-3] = s.data[t-3], s.data[t]
			}
		case opcode.SWAP4:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 4 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-4] = s.data[t-4], s.data[t]
			}
		case opcode.SWAP5:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 5 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-5] = s.data[t-5], s.data[t]
			}
		case opcode.SWAP6:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 6 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-6] = s.data[t-6], s.data[t]
			}
		case opcode.SWAP7:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 7 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-7] = s.data[t-7], s.data[t]
			}
		case opcode.SWAP8:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 8 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-8] = s.data[t-8], s.data[t]
			}
		case opcode.SWAP9:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 9 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-9] = s.data[t-9], s.data[t]
			}
		case opcode.SWAP10:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 10 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-10] = s.data[t-10], s.data[t]
			}
		case opcode.SWAP11:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 11 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-11] = s.data[t-11], s.data[t]
			}
		case opcode.SWAP12:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 12 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-12] = s.data[t-12], s.data[t]
			}
		case opcode.SWAP13:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 13 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-13] = s.data[t-13], s.data[t]
			}
		case opcode.SWAP14:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 14 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-14] = s.data[t-14], s.data[t]
			}
		case opcode.SWAP15:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 15 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-15] = s.data[t-15], s.data[t]
			}
		case opcode.SWAP16:
			gasCounter += spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 16 {
				if gas.remaining < gasCounter {
					interp.HaltOOG()
					return
				}
				gas.remaining -= gasCounter
				gasCounter = 0
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-16] = s.data[t-16], s.data[t]
			}
		case opcode.LOG0:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			logNImpl(interp, host, 0)
		case opcode.LOG1:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			logNImpl(interp, host, 1)
		case opcode.LOG2:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			logNImpl(interp, host, 2)
		case opcode.LOG3:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			logNImpl(interp, host, 3)
		case opcode.LOG4:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			logNImpl(interp, host, 4)
		default:
			if gas.remaining < gasCounter {
				interp.HaltOOG()
				return
			}
			gas.remaining -= gasCounter
			gasCounter = 0
			interp.Halt(InstructionResultOpcodeNotFound)
		}
	}
}

// Run executes bytecode with per-opcode tracing hooks.
// Unlike DefaultRunner.Run, there is no gas accumulator — each opcode
// deducts its static gas immediately, so the tracer receives accurate
// gas and cost values in OnOpcode callbacks.
// If Hooks.OnOpcode is nil, delegates to DefaultRunner for the fast path.
func (r *TracingRunner) Run(interp *Interpreter, host Host) {
	if r.Hooks == nil || r.Hooks.OnOpcode == nil {
		DefaultRunner{}.Run(interp, host)
		return
	}
	bc := interp.Bytecode
	gas := &interp.Gas
	hooks := r.Hooks
	dgt := r.DebugGasTable
	for bc.running {
		op := bc.code[bc.pc]
		bc.pc++

		// OnOpcode: report to tracer before execution.
		// gas.remaining is pre-deduction; debugCost is the base static cost.
		var debugCost uint64
		if dgt != nil {
			debugCost = dgt[op]
		}
		hooks.OnOpcode(uint64(bc.pc-1), op, gas.remaining, debugCost,
			interp, interp.ReturnData, interp.Depth+1, nil)

		switch op {
		case opcode.STOP:

			interp.Halt(InstructionResultStop)

		case opcode.ADD:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				types.AddTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.MUL:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				top.Mul(&a, top)

			}
		case opcode.SUB:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				types.SubTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.DIV:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				if !types.IsZeroPtr(top) {
					top.Div(&a, top)
				}

			}
		case opcode.SDIV:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				*top = types.SDiv(a, *top)

			}
		case opcode.MOD:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				if !types.IsZeroPtr(top) {
					top.Mod(&a, top)
				}

			}
		case opcode.SMOD:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				*top = types.SMod(a, *top)

			}
		case opcode.ADDMOD:
			if gas.remaining < spec.GasMid {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasMid
			s := interp.Stack
			if s.top < 3 {
				interp.HaltUnderflow()
			} else {
				s.top -= 2

				a := s.data[s.top+1]
				b := s.data[s.top]
				top := &s.data[s.top-1]
				top.AddMod(&a, &b, top)

			}
		case opcode.MULMOD:
			if gas.remaining < spec.GasMid {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasMid
			s := interp.Stack
			if s.top < 3 {
				interp.HaltUnderflow()
			} else {
				s.top -= 2

				a := s.data[s.top+1]
				b := s.data[s.top]
				top := &s.data[s.top-1]
				top.MulMod(&a, &b, top)

			}
		case opcode.EXP:
			if gas.remaining < spec.GasHigh {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasHigh
			opExp(interp)
		case opcode.SIGNEXTEND:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				ext := s.data[s.top]
				top := &s.data[s.top-1]
				*top = types.SignExtend(ext, *top)

			}
		case opcode.LT:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				if types.LtPtr(&s.data[s.top], &s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.GT:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				if types.GtPtr(&s.data[s.top], &s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.SLT:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := &s.data[s.top]
				b := &s.data[s.top-1]
				aNeg := a[3] >> 63
				bNeg := b[3] >> 63
				var lt bool
				if aNeg != bNeg {
					lt = aNeg > bNeg
				} else {
					lt = types.LtPtr(a, b)
				}
				if lt {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.SGT:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := &s.data[s.top]
				b := &s.data[s.top-1]
				aNeg := a[3] >> 63
				bNeg := b[3] >> 63
				var gt bool
				if aNeg != bNeg {
					gt = bNeg > aNeg
				} else {
					gt = types.GtPtr(a, b)
				}
				if gt {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.EQ:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				if types.EqPtr(&s.data[s.top], &s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.ISZERO:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
			} else {

				if types.IsZeroPtr(&s.data[s.top-1]) {
					s.data[s.top-1] = types.U256One
				} else {
					s.data[s.top-1] = types.U256Zero
				}

			}
		case opcode.AND:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				types.AndTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.OR:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				types.OrTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.XOR:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				types.XorTo(&s.data[s.top-1], &s.data[s.top], &s.data[s.top-1])

			}
		case opcode.NOT:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
			} else {

				types.NotTo(&s.data[s.top-1], &s.data[s.top-1])

			}
		case opcode.BYTE:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
			} else {
				s.top--

				a := s.data[s.top]
				top := &s.data[s.top-1]
				idx := types.U256AsUsizeSaturated(&a)
				if idx < 32 {
					*top = types.U256From(uint64(types.U256ByteBE(top, uint(idx))))
				} else {
					*top = types.U256Zero
				}

			}
		case opcode.SHL:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top < 2 {
					interp.HaltUnderflow()
				} else {
					s.top--

					shift := s.data[s.top]
					top := &s.data[s.top-1]
					sa := types.U256AsUsizeSaturated(&shift)
					if sa < 256 {
						top.Lsh(top, uint(sa))
					} else {
						*top = types.U256Zero
					}

				}
			}
		case opcode.SHR:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top < 2 {
					interp.HaltUnderflow()
				} else {
					s.top--

					shift := s.data[s.top]
					top := &s.data[s.top-1]
					sa := types.U256AsUsizeSaturated(&shift)
					if sa < 256 {
						top.Rsh(top, uint(sa))
					} else {
						*top = types.U256Zero
					}

				}
			}
		case opcode.SAR:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top < 2 {
					interp.HaltUnderflow()
				} else {
					s.top--

					shift := s.data[s.top]
					top := &s.data[s.top-1]
					sa := types.U256AsUsizeSaturated(&shift)
					if sa < 256 {
						top.SRsh(top, uint(sa))
					} else if types.U256Bit(top, 255) {
						*top = types.U256Max
					} else {
						*top = types.U256Zero
					}

				}
			}
		case opcode.CLZ:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Osaka) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top == 0 {
					interp.HaltUnderflow()
				} else {

					top := &s.data[s.top-1]
					*top = types.U256From(uint64(types.U256LeadingZeros(top)))

				}
			}
		case opcode.KECCAK256:
			if gas.remaining < spec.GasKeccak256 {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasKeccak256
			opKeccak256(interp)
		case opcode.ADDRESS:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = interp.Input.TargetAddress.ToU256()
				s.top++

			}
		case opcode.BALANCE:
			if gas.remaining < interp.ForkGas.Balance {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Balance
			opBalance(interp, host)
		case opcode.ORIGIN:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				addr := host.Caller()
				s.data[s.top] = addr.ToU256()
				s.top++

			}
		case opcode.CALLER:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = interp.Input.CallerAddress.ToU256()
				s.top++

			}
		case opcode.CALLVALUE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = interp.Input.CallValue
				s.top++

			}
		case opcode.CALLDATALOAD:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
			} else {

				top := &s.data[s.top-1]
				offset := types.U256AsUsizeSaturated(top)
				input := interp.Input.Input
				var word [32]byte
				if offset < uint64(len(input)) {
					src := input[offset:]
					if len(src) >= 32 {
						copy(word[:], src[:32])
					} else {
						copy(word[:], src)
					}
				}
				*top = types.U256FromBytes32(word)

			}
		case opcode.CALLDATASIZE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(len(interp.Input.Input)))
				s.top++

			}
		case opcode.CALLDATACOPY:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			opCalldatacopy(interp)
		case opcode.CODESIZE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(bc.originalLen))
				s.top++

			}
		case opcode.CODECOPY:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			opCodecopy(interp)
		case opcode.GASPRICE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.EffectiveGasPrice()
				s.top++

			}
		case opcode.EXTCODESIZE:
			if gas.remaining < interp.ForkGas.ExtCodeSize {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.ExtCodeSize
			opExtcodesize(interp, host)
		case opcode.EXTCODECOPY:
			if gas.remaining < interp.ForkGas.ExtCodeSize {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.ExtCodeSize
			opExtcodecopy(interp, host)
		case opcode.RETURNDATASIZE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {

					s.data[s.top] = types.U256From(uint64(len(interp.ReturnData)))
					s.top++

				}
			}
		case opcode.RETURNDATACOPY:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				opReturndatacopy(interp)
			}
		case opcode.EXTCODEHASH:
			if gas.remaining < interp.ForkGas.ExtCodeHash {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.ExtCodeHash
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Constantinople) {
				interp.HaltNotActivated()
			} else {
				opExtcodehash(interp, host)
			}
		case opcode.BLOCKHASH:
			if gas.remaining < spec.GasBlockhash {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBlockhash
			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
			} else {

				top := &s.data[s.top-1]
				hash := host.BlockHash(*top)
				*top = hash.ToU256()

			}
		case opcode.COINBASE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				addr := host.Beneficiary()
				s.data[s.top] = addr.ToU256()
				s.top++

			}
		case opcode.TIMESTAMP:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.Timestamp()
				s.top++

			}
		case opcode.NUMBER:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.BlockNumber()
				s.top++

			}
		case opcode.DIFFICULTY:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			opDifficulty(interp, host)
		case opcode.GASLIMIT:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = host.GasLimit()
				s.top++

			}
		case opcode.CHAINID:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Istanbul) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {
					opChainid(interp, host)
				}
			}
		case opcode.SELFBALANCE:
			if gas.remaining < spec.GasLow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasLow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Istanbul) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {
					opSelfbalance(interp, host)
				}
			}
		case opcode.BASEFEE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.London) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {
					opBasefee(interp, host)
				}
			}
		case opcode.BLOBHASH:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opBlobhash(interp, host)
			}
		case opcode.BLOBBASEFEE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {
					opBlobbasefee(interp, host)
				}
			}
		case opcode.SLOTNUM:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {
					opSlotnum(interp, host)
				}
			}
		case opcode.POP:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if interp.Stack.top == 0 {
				interp.HaltUnderflow()
			} else {

				interp.Stack.top--

			}
		case opcode.MLOAD:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow

			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
				return
			}
			top := &s.data[s.top-1]
			if top[1]|top[2]|top[3] == 0 {
				offset := int(top[0])
				if offset >= 0 && offset+32 <= interp.Memory.Len() {
					*top = interp.Memory.GetU256(offset)
				} else {
					if interp.ResizeMemory(offset, 32) {
						*top = interp.Memory.GetU256(offset)
					}
				}
			} else {
				interp.Halt(InstructionResultInvalidOperandOOG)
			}

		case opcode.MSTORE:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow

			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
				return
			}
			s.top -= 2
			offsetVal := s.data[s.top+1]
			value := s.data[s.top]
			if offsetVal[1]|offsetVal[2]|offsetVal[3] == 0 {
				offset := int(offsetVal[0])
				if offset >= 0 && offset+32 <= interp.Memory.Len() {
					interp.Memory.SetU256(offset, value)
				} else {
					if interp.ResizeMemory(offset, 32) {
						interp.Memory.SetU256(offset, value)
					}
				}
			} else {
				interp.Halt(InstructionResultInvalidOperandOOG)
			}

		case opcode.MSTORE8:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			opMstore8(interp)
		case opcode.SLOAD:
			if gas.remaining < interp.ForkGas.Sload {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Sload
			opSload(interp, host)
		case opcode.SSTORE:
			opSstore(interp, host)
		case opcode.JUMP:
			if gas.remaining < spec.GasMid {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasMid

			s := interp.Stack
			if s.top == 0 {
				interp.HaltUnderflow()
				return
			}
			s.top--
			target := s.data[s.top]
			if target[1]|target[2]|target[3] != 0 {
				interp.Halt(InstructionResultInvalidJump)
				return
			}
			dest := int(target[0])
			bc := bc
			if dest >= bc.originalLen || bc.code[dest] != opcode.JUMPDEST {
				interp.Halt(InstructionResultInvalidJump)
				return
			}
			bc.ensureJumpTable()
			if bc.jumpTable[dest/8]&(1<<(uint(dest)%8)) == 0 {
				interp.Halt(InstructionResultInvalidJump)
				return
			}
			bc.pc = dest

		case opcode.JUMPI:
			if gas.remaining < spec.GasHigh {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasHigh

			s := interp.Stack
			if s.top < 2 {
				interp.HaltUnderflow()
				return
			}
			s.top -= 2
			cond := s.data[s.top]
			target := s.data[s.top+1]
			if !cond.IsZero() {
				if target[1]|target[2]|target[3] != 0 {
					interp.Halt(InstructionResultInvalidJump)
					return
				}
				dest := int(target[0])
				bc := bc
				if dest >= bc.originalLen || bc.code[dest] != opcode.JUMPDEST {
					interp.Halt(InstructionResultInvalidJump)
					return
				}
				bc.ensureJumpTable()
				if bc.jumpTable[dest/8]&(1<<(uint(dest)%8)) == 0 {
					interp.Halt(InstructionResultInvalidJump)
					return
				}
				bc.pc = dest
			}

		case opcode.PC:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(bc.pc - 1))
				s.top++

			}
		case opcode.MSIZE:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = types.U256From(uint64(interp.Memory.Len()))
				s.top++

			}
		case opcode.GAS:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			opGas(interp)
		case opcode.JUMPDEST:
			if gas.remaining < spec.GasJumpdest {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasJumpdest
		case opcode.TLOAD:
			if gas.remaining < spec.GasWarmStorageReadCost {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasWarmStorageReadCost
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opTload(interp, host)
			}
		case opcode.TSTORE:
			if gas.remaining < spec.GasWarmStorageReadCost {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasWarmStorageReadCost
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opTstore(interp, host)
			}
		case opcode.MCOPY:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Cancun) {
				interp.HaltNotActivated()
			} else {
				opMcopy(interp)
			}
		case opcode.DUPN:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				opDupN(interp)
			}
		case opcode.SWAPN:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				opSwapN(interp)
			}
		case opcode.EXCHANGE:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Amsterdam) {
				interp.HaltNotActivated()
			} else {
				opExchange(interp)
			}
		case opcode.CREATE:
			opCreate(interp, host)
		case opcode.CALL:
			if gas.remaining < interp.ForkGas.Call {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Call
			opCall(interp, host)
		case opcode.CALLCODE:
			if gas.remaining < interp.ForkGas.Call {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Call
			opCallcode(interp, host)
		case opcode.RETURN:
			opReturn(interp)
		case opcode.DELEGATECALL:
			if gas.remaining < interp.ForkGas.Call {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Call
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Homestead) {
				interp.HaltNotActivated()
			} else {
				opDelegatecall(interp, host)
			}
		case opcode.CREATE2:
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Petersburg) {
				interp.HaltNotActivated()
			} else {
				opCreate2(interp, host)
			}
		case opcode.STATICCALL:
			if gas.remaining < interp.ForkGas.Call {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Call
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				opStaticcall(interp, host)
			}
		case opcode.REVERT:
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Byzantium) {
				interp.HaltNotActivated()
			} else {
				opRevert(interp)
			}
		case opcode.INVALID:

			interp.Halt(InstructionResultInvalidFEOpcode)

		case opcode.SELFDESTRUCT:
			if gas.remaining < interp.ForkGas.Selfdestruct {
				interp.HaltOOG()
				return
			}
			gas.remaining -= interp.ForkGas.Selfdestruct
			opSelfdestruct(interp, host)
		case opcode.PUSH0:
			if gas.remaining < spec.GasBase {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasBase
			if !interp.RuntimeFlag.ForkID.IsEnabledIn(spec.Shanghai) {
				interp.HaltNotActivated()
			} else {
				s := interp.Stack
				if s.top >= StackLimit {
					interp.HaltOverflow()
				} else {

					s.data[s.top] = types.U256Zero
					s.top++

				}
			}
		case opcode.PUSH1:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				s.data[s.top] = uint256.Int{uint64(bc.code[bc.pc]), 0, 0, 0}
				bc.pc++
				s.top++

			}
		case opcode.PUSH2:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				v := uint64(bc.code[bc.pc])<<8 | uint64(bc.code[bc.pc+1])
				bc.pc += 2
				s.data[s.top] = uint256.Int{v, 0, 0, 0}
				s.top++

			}
		case opcode.PUSH3:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				v := uint64(c[p])<<16 | uint64(c[p+1])<<8 | uint64(c[p+2])
				bc.pc = p + 3
				s.data[s.top] = uint256.Int{v, 0, 0, 0}
				s.top++

			}
		case opcode.PUSH4:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				v := uint64(c[p])<<24 | uint64(c[p+1])<<16 | uint64(c[p+2])<<8 | uint64(c[p+3])
				bc.pc = p + 4
				s.data[s.top] = uint256.Int{v, 0, 0, 0}
				s.top++

			}
		case opcode.PUSH20:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				// 20 bytes = limb2 (4 bytes) + limb1 (8 bytes) + limb0 (8 bytes)
				l2 := uint64(c[p])<<24 | uint64(c[p+1])<<16 | uint64(c[p+2])<<8 | uint64(c[p+3])
				l1 := uint64(c[p+4])<<56 | uint64(c[p+5])<<48 | uint64(c[p+6])<<40 | uint64(c[p+7])<<32 |
					uint64(c[p+8])<<24 | uint64(c[p+9])<<16 | uint64(c[p+10])<<8 | uint64(c[p+11])
				l0 := uint64(c[p+12])<<56 | uint64(c[p+13])<<48 | uint64(c[p+14])<<40 | uint64(c[p+15])<<32 |
					uint64(c[p+16])<<24 | uint64(c[p+17])<<16 | uint64(c[p+18])<<8 | uint64(c[p+19])
				bc.pc = p + 20
				s.data[s.top] = uint256.Int{l0, l1, l2, 0}
				s.top++

			}
		case opcode.PUSH32:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {

				c := bc.code
				p := bc.pc
				l3 := uint64(c[p])<<56 | uint64(c[p+1])<<48 | uint64(c[p+2])<<40 | uint64(c[p+3])<<32 |
					uint64(c[p+4])<<24 | uint64(c[p+5])<<16 | uint64(c[p+6])<<8 | uint64(c[p+7])
				l2 := uint64(c[p+8])<<56 | uint64(c[p+9])<<48 | uint64(c[p+10])<<40 | uint64(c[p+11])<<32 |
					uint64(c[p+12])<<24 | uint64(c[p+13])<<16 | uint64(c[p+14])<<8 | uint64(c[p+15])
				l1 := uint64(c[p+16])<<56 | uint64(c[p+17])<<48 | uint64(c[p+18])<<40 | uint64(c[p+19])<<32 |
					uint64(c[p+20])<<24 | uint64(c[p+21])<<16 | uint64(c[p+22])<<8 | uint64(c[p+23])
				l0 := uint64(c[p+24])<<56 | uint64(c[p+25])<<48 | uint64(c[p+26])<<40 | uint64(c[p+27])<<32 |
					uint64(c[p+28])<<24 | uint64(c[p+29])<<16 | uint64(c[p+30])<<8 | uint64(c[p+31])
				bc.pc = p + 32
				s.data[s.top] = uint256.Int{l0, l1, l2, l3}
				s.top++

			}
		case opcode.PUSH5, opcode.PUSH6, opcode.PUSH7, opcode.PUSH8, opcode.PUSH9, opcode.PUSH10, opcode.PUSH11, opcode.PUSH12, opcode.PUSH13, opcode.PUSH14, opcode.PUSH15, opcode.PUSH16, opcode.PUSH17, opcode.PUSH18, opcode.PUSH19, opcode.PUSH21, opcode.PUSH22, opcode.PUSH23, opcode.PUSH24, opcode.PUSH25, opcode.PUSH26, opcode.PUSH27, opcode.PUSH28, opcode.PUSH29, opcode.PUSH30, opcode.PUSH31:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				n := int(op - opcode.PUSH0)
				s.data[s.top] = types.U256FromBytes(bc.code[bc.pc : bc.pc+n])
				bc.pc += n
				s.top++
			}
		case opcode.DUP1:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 1 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-1]
				s.top++
			}
		case opcode.DUP2:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 2 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-2]
				s.top++
			}
		case opcode.DUP3:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 3 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-3]
				s.top++
			}
		case opcode.DUP4:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 4 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-4]
				s.top++
			}
		case opcode.DUP5:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 5 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-5]
				s.top++
			}
		case opcode.DUP6:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 6 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-6]
				s.top++
			}
		case opcode.DUP7:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 7 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-7]
				s.top++
			}
		case opcode.DUP8:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 8 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-8]
				s.top++
			}
		case opcode.DUP9:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 9 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-9]
				s.top++
			}
		case opcode.DUP10:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 10 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-10]
				s.top++
			}
		case opcode.DUP11:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 11 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-11]
				s.top++
			}
		case opcode.DUP12:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 12 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-12]
				s.top++
			}
		case opcode.DUP13:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 13 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-13]
				s.top++
			}
		case opcode.DUP14:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 14 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-14]
				s.top++
			}
		case opcode.DUP15:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 15 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-15]
				s.top++
			}
		case opcode.DUP16:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			if s.top < 16 || s.top >= StackLimit {
				interp.HaltOverflow()
			} else {
				s.data[s.top] = s.data[s.top-16]
				s.top++
			}
		case opcode.SWAP1:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 1 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-1] = s.data[t-1], s.data[t]
			}
		case opcode.SWAP2:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 2 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-2] = s.data[t-2], s.data[t]
			}
		case opcode.SWAP3:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 3 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-3] = s.data[t-3], s.data[t]
			}
		case opcode.SWAP4:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 4 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-4] = s.data[t-4], s.data[t]
			}
		case opcode.SWAP5:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 5 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-5] = s.data[t-5], s.data[t]
			}
		case opcode.SWAP6:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 6 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-6] = s.data[t-6], s.data[t]
			}
		case opcode.SWAP7:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 7 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-7] = s.data[t-7], s.data[t]
			}
		case opcode.SWAP8:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 8 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-8] = s.data[t-8], s.data[t]
			}
		case opcode.SWAP9:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 9 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-9] = s.data[t-9], s.data[t]
			}
		case opcode.SWAP10:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 10 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-10] = s.data[t-10], s.data[t]
			}
		case opcode.SWAP11:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 11 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-11] = s.data[t-11], s.data[t]
			}
		case opcode.SWAP12:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 12 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-12] = s.data[t-12], s.data[t]
			}
		case opcode.SWAP13:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 13 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-13] = s.data[t-13], s.data[t]
			}
		case opcode.SWAP14:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 14 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-14] = s.data[t-14], s.data[t]
			}
		case opcode.SWAP15:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 15 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-15] = s.data[t-15], s.data[t]
			}
		case opcode.SWAP16:
			if gas.remaining < spec.GasVerylow {
				interp.HaltOOG()
				return
			}
			gas.remaining -= spec.GasVerylow
			s := interp.Stack
			t := s.top - 1
			if t < 16 {
				interp.HaltOverflow()
			} else {
				s.data[t], s.data[t-16] = s.data[t-16], s.data[t]
			}
		case opcode.LOG0:
			logNImpl(interp, host, 0)
		case opcode.LOG1:
			logNImpl(interp, host, 1)
		case opcode.LOG2:
			logNImpl(interp, host, 2)
		case opcode.LOG3:
			logNImpl(interp, host, 3)
		case opcode.LOG4:
			logNImpl(interp, host, 4)
		default:
			interp.Halt(InstructionResultOpcodeNotFound)
		}
		if !bc.running && interp.HaltResult.IsError() {
			if hooks.OnFault != nil {
				var faultCost uint64
				if dgt != nil {
					faultCost = dgt[op]
				}
				hooks.OnFault(uint64(bc.pc-1), op, gas.remaining, faultCost,
					interp, interp.Depth+1, nil)
			}
		}
	}
}

// buildDebugGasTable constructs a per-opcode static gas cost table.
// Used by the tracer to report cost in OnOpcode/OnFault hooks.
func buildDebugGasTable(fg ForkGas) [256]uint64 {
	var t [256]uint64
	t[0x01] = spec.GasVerylow             // ADD
	t[0x02] = spec.GasLow                 // MUL
	t[0x03] = spec.GasVerylow             // SUB
	t[0x04] = spec.GasLow                 // DIV
	t[0x05] = spec.GasLow                 // SDIV
	t[0x06] = spec.GasLow                 // MOD
	t[0x07] = spec.GasLow                 // SMOD
	t[0x08] = spec.GasMid                 // ADDMOD
	t[0x09] = spec.GasMid                 // MULMOD
	t[0x0A] = spec.GasHigh                // EXP
	t[0x0B] = spec.GasLow                 // SIGNEXTEND
	t[0x10] = spec.GasVerylow             // LT
	t[0x11] = spec.GasVerylow             // GT
	t[0x12] = spec.GasVerylow             // SLT
	t[0x13] = spec.GasVerylow             // SGT
	t[0x14] = spec.GasVerylow             // EQ
	t[0x15] = spec.GasVerylow             // ISZERO
	t[0x16] = spec.GasVerylow             // AND
	t[0x17] = spec.GasVerylow             // OR
	t[0x18] = spec.GasVerylow             // XOR
	t[0x19] = spec.GasVerylow             // NOT
	t[0x1A] = spec.GasVerylow             // BYTE
	t[0x1B] = spec.GasVerylow             // SHL
	t[0x1C] = spec.GasVerylow             // SHR
	t[0x1D] = spec.GasVerylow             // SAR
	t[0x1E] = spec.GasLow                 // CLZ
	t[0x20] = spec.GasKeccak256           // KECCAK256
	t[0x30] = spec.GasBase                // ADDRESS
	t[0x31] = fg.Balance                  // BALANCE
	t[0x32] = spec.GasBase                // ORIGIN
	t[0x33] = spec.GasBase                // CALLER
	t[0x34] = spec.GasBase                // CALLVALUE
	t[0x35] = spec.GasVerylow             // CALLDATALOAD
	t[0x36] = spec.GasBase                // CALLDATASIZE
	t[0x37] = spec.GasVerylow             // CALLDATACOPY
	t[0x38] = spec.GasBase                // CODESIZE
	t[0x39] = spec.GasVerylow             // CODECOPY
	t[0x3A] = spec.GasBase                // GASPRICE
	t[0x3B] = fg.ExtCodeSize              // EXTCODESIZE
	t[0x3C] = fg.ExtCodeSize              // EXTCODECOPY
	t[0x3D] = spec.GasBase                // RETURNDATASIZE
	t[0x3E] = spec.GasVerylow             // RETURNDATACOPY
	t[0x3F] = fg.ExtCodeHash              // EXTCODEHASH
	t[0x40] = spec.GasBlockhash           // BLOCKHASH
	t[0x41] = spec.GasBase                // COINBASE
	t[0x42] = spec.GasBase                // TIMESTAMP
	t[0x43] = spec.GasBase                // NUMBER
	t[0x44] = spec.GasBase                // DIFFICULTY
	t[0x45] = spec.GasBase                // GASLIMIT
	t[0x46] = spec.GasBase                // CHAINID
	t[0x47] = spec.GasLow                 // SELFBALANCE
	t[0x48] = spec.GasBase                // BASEFEE
	t[0x49] = spec.GasVerylow             // BLOBHASH
	t[0x4A] = spec.GasBase                // BLOBBASEFEE
	t[0x4B] = spec.GasBase                // SLOTNUM
	t[0x50] = spec.GasBase                // POP
	t[0x51] = spec.GasVerylow             // MLOAD
	t[0x52] = spec.GasVerylow             // MSTORE
	t[0x53] = spec.GasVerylow             // MSTORE8
	t[0x54] = fg.Sload                    // SLOAD
	t[0x56] = spec.GasMid                 // JUMP
	t[0x57] = spec.GasHigh                // JUMPI
	t[0x58] = spec.GasBase                // PC
	t[0x59] = spec.GasBase                // MSIZE
	t[0x5A] = spec.GasBase                // GAS
	t[0x5B] = spec.GasJumpdest            // JUMPDEST
	t[0x5C] = spec.GasWarmStorageReadCost // TLOAD
	t[0x5D] = spec.GasWarmStorageReadCost // TSTORE
	t[0x5E] = spec.GasVerylow             // MCOPY
	t[0xE6] = spec.GasVerylow             // DUPN
	t[0xE7] = spec.GasVerylow             // SWAPN
	t[0xE8] = spec.GasVerylow             // EXCHANGE
	t[0xF1] = fg.Call                     // CALL
	t[0xF2] = fg.Call                     // CALLCODE
	t[0xF4] = fg.Call                     // DELEGATECALL
	t[0xFA] = fg.Call                     // STATICCALL
	t[0xFF] = fg.Selfdestruct             // SELFDESTRUCT
	t[0x5F] = spec.GasBase                // PUSH0
	for i := byte(0x60); i <= 0x7F; i++ {
		t[i] = spec.GasVerylow
	} // PUSH1-PUSH32
	for i := byte(0x80); i <= 0x8F; i++ {
		t[i] = spec.GasVerylow
	} // DUP1-DUP16
	for i := byte(0x90); i <= 0x9F; i++ {
		t[i] = spec.GasVerylow
	} // SWAP1-SWAP16
	for i := byte(0xA0); i <= 0xA4; i++ {
		t[i] = spec.GasLog
	} // LOG0-LOG4
	return t
}

// DebugGasTableForFork returns a per-opcode static gas table for the given fork.
// Allocated once per tracing session; cost is negligible.
func DebugGasTableForFork(forkID spec.ForkID) *[256]uint64 {
	t := buildDebugGasTable(NewForkGas(forkID))
	return &t
}
